// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQQmkWUX1vUqfs1ykHPc7OqCx2cAEKB-U',
    appId: '1:433011638463:web:5c362e80d8c25621a5c60a',
    messagingSenderId: '433011638463',
    projectId: 'tempprojcte',
    authDomain: 'tempprojcte.firebaseapp.com',
    storageBucket: 'tempprojcte.appspot.com',
    measurementId: 'G-FE6Z675C0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoC8qn6jhPDEtaDEM35_b8vYfEu1cBjr0',
    appId: '1:433011638463:android:19f29bad2273aff2a5c60a',
    messagingSenderId: '433011638463',
    projectId: 'tempprojcte',
    storageBucket: 'tempprojcte.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0wGlpODZNcVtWCirCXYPAOE74gXrn1-I',
    appId: '1:433011638463:ios:43508ccd2d24886ea5c60a',
    messagingSenderId: '433011638463',
    projectId: 'tempprojcte',
    storageBucket: 'tempprojcte.appspot.com',
    iosClientId: '433011638463-vaoj5t0nal5eelgk0ci64u2atnjr2je8.apps.googleusercontent.com',
    iosBundleId: 'com.example.tempProject',
  );
}
